# fly.toml app configuration file generated for betchess on 2026-04-25T20:49:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "betchess"
primary_region = "ams"

[build]

[env]
  HOST = "0.0.0.0"
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 50

[[http_service.checks]]
  grace_period = "10s"
  interval = "15s"
  method = "GET"
  timeout = "5s"
  path = "/healthz"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
